import authRoutes from "../routes/authRoutes.js";
import likeRoutes from "../routes/likeRoutes.js";
import productRoutes from "../routes/productRoutes.js";
import categoryRoutes from "../routes/categoryRoutes.js";
import subCategoryRoutes from "../routes/subCategoryRoutes.js";
import reviewRoutes from "../routes/reviewRoutes.js";
import cartRoutes from "../routes/cartRoutes.js";
import translationRoutes from "../routes/translations.js";
import locationRoutes from "../routes/locationRoutes.js";
import specConfigRoutes from "../routes/specConfigRoutes.js";
import specTemplateRoutes from "../routes/specTemplateRoutes.js";
import orderRoutes from "../routes/orderRoutes.js";
import messageRoutes from "../routes/messageRoutes.js";
import chatRoutes from "../routes/chatRoutes.js";
import adminRoutes from "../routes/adminRoutes.js";
import userRoutes from "../routes/userRoutes.js";
import heartbeatRoutes from "../routes/heartbeatRoutes.js";
import i18nMissingRoutes from "../routes/i18nMissingRoutes.js";
import inventoryRoutes from "../routes/inventoryRoutes.js";

export const registerApiRoutes = (app) => {
  app.use("/api/auth", authRoutes);
  app.use("/api/likes", likeRoutes);
  app.use("/api/products", productRoutes);
  app.use("/api/categories", categoryRoutes);
  app.use("/api/subcategories", subCategoryRoutes);
  app.use("/api/reviews", reviewRoutes);
  app.use("/api/cart", cartRoutes);
  app.use("/api/translations", translationRoutes);
  app.use("/api/locations", locationRoutes);
  app.use("/api/spec-config", specConfigRoutes);
  app.use("/api/spec-templates", specTemplateRoutes);
  app.use("/api/orders", orderRoutes);
  app.use("/api/messages", messageRoutes);
  app.use("/api/chat", chatRoutes);
  app.use("/api/inventory", inventoryRoutes);
  app.use("/api/admin", adminRoutes);
  app.use("/api/users", userRoutes);
  app.use("/api/heartbeat", heartbeatRoutes);
  app.use("/api/i18n-missing", i18nMissingRoutes);
};
